services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672" # Interface web (dashboard)
      #http://localhost:15672 user: guest pass: guest

  gateway:
    build:
      context: .
      args:
        SERVICE_NAME: gateway
    env_file:
      - .env
    container_name: gateway
    command: python  micro_services/gateway_service.py
    depends_on:
      - rabbitmq

  promotion:
    build:
      context: .
      args:
        SERVICE_NAME: promotion
    env_file:
      - .env
    container_name: promotion
    command: python  micro_services/promotion_service.py
    depends_on:
      - rabbitmq

  ranking:
    build:
      context: .
      args:
        SERVICE_NAME: ranking
    env_file:
      - .env
    container_name: ranking
    command: python  micro_services/ranking_service.py
    depends_on:
      - rabbitmq

  notification:
    build:
      context: .
      args:
        SERVICE_NAME: notification
    env_file:
      - .env
    container_name: notification
    command: python  micro_services/notification_service.py
    depends_on:
      - rabbitmq

  client1:
    build:
      context: .
      args:
        SERVICE_NAME: client1
    env_file:
      - .env
    environment:
      CLIENT_ID: 1
    container_name: client1
    command: python  client.py
    depends_on:
      - rabbitmq

  client2:
    build:
      context: .
      args:
        SERVICE_NAME: client2
    env_file:
      - .env
    environment:
      CLIENT_ID: 2
    container_name: client2
    command: python  client.py
    depends_on:
      - rabbitmq